# Generated by Django 5.0 on 2024-11-17 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ClearPay', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='country',
        ),
    ]
