# Generated by Django 5.0 on 2024-11-18 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClearPay', '0002_remove_client_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='repayment_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
