# Generated by Django 5.0 on 2024-11-18 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ClearPay', '0004_loan_due_date_loan_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='transaction_type',
        ),
    ]
