# Generated by Django 5.0 on 2024-11-18 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClearPay', '0005_remove_transaction_transaction_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('loan', 'Loan'), ('repayment', 'Repayment')], default='loan', max_length=10),
        ),
    ]
